//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistem.manajemen.ppic.dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PPICEntities : DbContext
    {
        public PPICEntities()
            : base("name=PPICEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Login> Logins { get; set; }
        public DbSet<PAGE> PAGEs { get; set; }
        public DbSet<MST_BARANG_JADI> MST_BARANG_JADI { get; set; }
        public DbSet<MST_WILAYAH> MST_WILAYAH { get; set; }
        public DbSet<CHANGES_HISTORY> CHANGES_HISTORY { get; set; }
        public DbSet<TRN_SPB> TRN_SPB { get; set; }
        public DbSet<TRN_DO> TRN_DO { get; set; }
        public DbSet<TRN_PENGIRIMAN> TRN_PENGIRIMAN { get; set; }
        public DbSet<HASIL_PRODUKSI> HASIL_PRODUKSI { get; set; }
    }
}
