//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistem.manajemen.ppic.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENT_NUMBER
    {
        public int ID { get; set; }
        public System.DateTime TANGGAL { get; set; }
        public Nullable<int> NO { get; set; }
        public Nullable<int> FORM_ID { get; set; }
    }
}
