//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistem.manajemen.ppic.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_KONSUMEN
    {
        public int ID { get; set; }
        public string NAMA_KONSUMEN { get; set; }
        public string ALAMAT_KONSUMEN { get; set; }
        public string CONTACT_PERSON { get; set; }
        public string NO_TELP { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string PERSONNO { get; set; }
    }
}
