//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistem.manajemen.ppic.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGE
    {
        public int PAGE_ID { get; set; }
        public string PAGE_NAME { get; set; }
        public string PAGE_URL { get; set; }
        public string MENU_NAME { get; set; }
        public Nullable<int> PARENT_PAGE_ID { get; set; }
    }
}
