//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistem.manajemen.ppic.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SO_BARANG_JADI
    {
        public SO_BARANG_JADI()
        {
            this.SO_BARANG_JADI_DETAILS = new HashSet<SO_BARANG_JADI_DETAILS>();
        }
    
        public int ID { get; set; }
        public System.DateTime TANGGAL { get; set; }
        public byte STATUS { get; set; }
        public string DOC_NUMBER { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
    
        public virtual ICollection<SO_BARANG_JADI_DETAILS> SO_BARANG_JADI_DETAILS { get; set; }
    }
}
