//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistem.manajemen.ppic.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SO_BARANG_JADI_DETAILS
    {
        public int ID { get; set; }
        public int ID_SO_BARANG_JADI { get; set; }
        public int ID_BARANG { get; set; }
        public decimal STOCK_SISTEM { get; set; }
        public decimal STOCK_REAL { get; set; }
        public decimal SELISIH { get; set; }
        public string KETERANGAN { get; set; }
    
        public virtual MST_BARANG_JADI MST_BARANG_JADI { get; set; }
        public virtual SO_BARANG_JADI SO_BARANG_JADI { get; set; }
    }
}
