//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistem.manajemen.ppic.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_PENGIRIMAN_DETAILS
    {
        public int ID { get; set; }
        public int ID_TRN_PENGIRIMAN_MASTER { get; set; }
        public int ID_BARANG { get; set; }
        public string URAIAN_BARANG { get; set; }
        public string KEMASAN { get; set; }
        public int ZAK { get; set; }
        public Nullable<decimal> STOCK_AWAL { get; set; }
        public decimal KUANTUM { get; set; }
        public Nullable<decimal> STOCK_AKHIR { get; set; }
        public string KETERANGAN { get; set; }
        public Nullable<byte> STATUS { get; set; }
    
        public virtual MST_BARANG_JADI MST_BARANG_JADI { get; set; }
        public virtual TRN_PENGIRIMAN_MASTER TRN_PENGIRIMAN_MASTER { get; set; }
    }
}
