//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistem.manajemen.ppic.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_SURAT_PERMINTAAN_BAHAN_BAKU_DETAILS
    {
        public int ID { get; set; }
        public int ID_TRN_SURAT_PERMINTAAN_BAHAN_BAKU { get; set; }
        public int ID_MST_BAHAN_BAKU { get; set; }
        public Nullable<decimal> KUANTUM { get; set; }
    
        public virtual MST_BAHAN_BAKU MST_BAHAN_BAKU { get; set; }
        public virtual TRN_SURAT_PERMINTAAN_BAHAN_BAKU TRN_SURAT_PERMINTAAN_BAHAN_BAKU { get; set; }
    }
}
