//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistem.manajemen.ppic.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_SURAT_PERMINTAAN_BAHAN_BAKU
    {
        public TRN_SURAT_PERMINTAAN_BAHAN_BAKU()
        {
            this.TRN_SURAT_PERMINTAAN_BAHAN_BAKU_DETAILS = new HashSet<TRN_SURAT_PERMINTAAN_BAHAN_BAKU_DETAILS>();
        }
    
        public int ID { get; set; }
        public System.DateTime TANGGAL { get; set; }
        public string NO_SPP { get; set; }
        public string NO_SURAT { get; set; }
        public string NAMA_PRODUK { get; set; }
        public string KOMPOSISI { get; set; }
        public string BENTUK { get; set; }
        public string KEMASAN { get; set; }
        public Nullable<int> SHIFT { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<byte> STATUS { get; set; }
        public string CATATAN { get; set; }
        public Nullable<decimal> KUANTUM_PRODUKSI { get; set; }
        public string REMARKS { get; set; }
    
        public virtual ICollection<TRN_SURAT_PERMINTAAN_BAHAN_BAKU_DETAILS> TRN_SURAT_PERMINTAAN_BAHAN_BAKU_DETAILS { get; set; }
    }
}
