//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistem.manajemen.ppic.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_PENERIMAAN_SUPPLIER
    {
        public TRN_PENERIMAAN_SUPPLIER()
        {
            this.TRN_PENERIMAAN_SUPPLIER_DETAILS = new HashSet<TRN_PENERIMAAN_SUPPLIER_DETAILS>();
        }
    
        public int ID { get; set; }
        public string NAMA_SUPPLIER { get; set; }
        public System.DateTime TANGGAL { get; set; }
        public string CATATAN { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string NO_POLISI { get; set; }
    
        public virtual ICollection<TRN_PENERIMAAN_SUPPLIER_DETAILS> TRN_PENERIMAAN_SUPPLIER_DETAILS { get; set; }
    }
}
