//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistem.manajemen.ppic.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKING_HOURS
    {
        public int ID { get; set; }
        public string NAMA { get; set; }
        public Nullable<System.DateTime> JAM_MULAI { get; set; }
        public Nullable<System.DateTime> JAM_SELESAI { get; set; }
        public Nullable<byte> STATUS { get; set; }
    }
}
