SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PAGE](
	[PAGE_ID] [int] IDENTITY(1,1) NOT NULL,
	[PAGE_NAME] [nvarchar](50) NULL,
	[PAGE_URL] [nvarchar](100) NULL,
	[MENU_NAME] [nvarchar](50) NULL,
	[PARENT_PAGE_ID] [int] NULL,
	[MAIN_TABLE] [nvarchar](100) NULL,
 CONSTRAINT [PK_PAGE] PRIMARY KEY CLUSTERED 
(
	[PAGE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]

GO


